-- Bills
game.AddDecal( "Bills1", "decals/bills01a" )
game.AddDecal( "Bills2", "decals/bills02a" )
game.AddDecal( "Bills3", "decals/bills03a" )
game.AddDecal( "Bills4", "decals/bills04a" )
game.AddDecal( "Bills5", "decals/bills05a" )

list.Add( "PaintMaterials", "Bills1" )
list.Add( "PaintMaterials", "Bills2" )
list.Add( "PaintMaterials", "Bills3" )
list.Add( "PaintMaterials", "Bills4" )
list.Add( "PaintMaterials", "Bills5" )

-- Bloodstains
game.AddDecal( "Bloodstain", { "decals/bloodstain_001", "decals/bloodstain_002", "decals/bloodstain_101" } )
game.AddDecal( "Bloodstain.Streak", "decals/bloodstain_003" )
game.AddDecal( "BloodStain.Alien", "decals/bloodstain_201" )

list.Add( "PaintMaterials", "Bloodstain" )
list.Add( "PaintMaterials", "Bloodstain.Streak" )
list.Add( "PaintMaterials", "BloodStain.Alien" )

-- Debris
game.AddDecal( "Debris.Concrete", { "decals/debris_concrete001a", "decals/debris_concrete001b" } )
game.AddDecal( "Debris.Tile", "decals/debris_tile001a" )
game.AddDecal( "Debris.Rubble", "decals/rubble01a" )
game.AddDecal( "Debris.Trash1", { "decals/trashdecal01a", "decals/trashdecal02a", "decals/trashdecal03a" } )
game.AddDecal( "Debris.Trash2", "decals/trashdecal04a" )
game.AddDecal( "Debris.Trash3", "decals/trashdecal05a" )
game.AddDecal( "Leaves", { "decals/leaves_ground01", "decals/leaves_ground02" } )
game.AddDecal( "Snow", "decals/ship_snow1b" )

list.Add( "PaintMaterials", "Debris.Concrete" )
list.Add( "PaintMaterials", "Debris.Tile" )
list.Add( "PaintMaterials", "Debris.Rubble" )
list.Add( "PaintMaterials", "Debris.Trash1" )
list.Add( "PaintMaterials", "Debris.Trash2" )
list.Add( "PaintMaterials", "Debris.Trash3" )
list.Add( "PaintMaterials", "Leaves" )
list.Add( "PaintMaterials", "Snow" )

-- Graffitti
game.AddDecal( "Graffitti001a", "decals/decalgraffiti001a" )
game.AddDecal( "Graffitti001b", "decals/decalgraffiti001b" )
game.AddDecal( "Graffitti001c", "decals/decalgraffiti001c" )
game.AddDecal( "Graffitti001d", "decals/decalgraffiti001d" )
game.AddDecal( "Graffitti003a", "decals/decalgraffiti003a" )
game.AddDecal( "Graffitti005a", "decals/decalgraffiti005a" )
game.AddDecal( "Graffitti006a", "decals/decalgraffiti006a" )
game.AddDecal( "Graffitti007a", "decals/decalgraffiti007a" )
game.AddDecal( "Graffitti008a", "decals/decalgraffiti008a" )
game.AddDecal( "Graffitti009a", "decals/decalgraffiti009a" )
game.AddDecal( "Graffitti010a", "decals/decalgraffiti010a" )
game.AddDecal( "Graffitti011a", "decals/decalgraffiti011a" )
game.AddDecal( "Graffitti012a", "decals/decalgraffiti012a" )
game.AddDecal( "Graffitti015a", "decals/decalgraffiti015a" )
game.AddDecal( "Graffitti017a", "decals/decalgraffiti017a" )
game.AddDecal( "Graffitti018a", "decals/decalgraffiti018a" )
game.AddDecal( "Graffitti020a", "decals/decalgraffiti020a" )
game.AddDecal( "Graffitti022a", "decals/decalgraffiti022a" )
game.AddDecal( "Graffitti023a", "decals/decalgraffiti023a" )
game.AddDecal( "Graffitti024a", "decals/decalgraffiti024a" )
game.AddDecal( "Graffitti025a", "decals/decalgraffiti025a" )
game.AddDecal( "Graffitti028a", "decals/decalgraffiti028a" )
game.AddDecal( "Graffitti031a", "decals/decalgraffiti031a" )
game.AddDecal( "Graffitti036a", "decals/decalgraffiti036a" )
game.AddDecal( "Graffitti037a", "decals/decalgraffiti037a" )
game.AddDecal( "Graffitti038a", "decals/decalgraffiti038a" )
game.AddDecal( "Graffitti043a", "decals/decalgraffiti043a" )
game.AddDecal( "Graffitti044a", "decals/decalgraffiti044a" )
game.AddDecal( "Graffitti046a", "decals/decalgraffiti046a" )
game.AddDecal( "Graffitti047a", "decals/decalgraffiti047a" )
game.AddDecal( "Graffitti049a", "decals/decalgraffiti049a" )
game.AddDecal( "Graffitti050a", "decals/decalgraffiti050a" )
game.AddDecal( "Graffitti054a", "decals/decalgraffiti054a" )
game.AddDecal( "Graffitti056a", "decals/decalgraffiti056a" )
game.AddDecal( "Graffitti059a", "decals/decalgraffiti059a" )
game.AddDecal( "Graffitti060a", "decals/decalgraffiti060a" )
game.AddDecal( "Graffitti061a", "decals/decalgraffiti061a" )
game.AddDecal( "Graffitti062a", "decals/decalgraffiti062a" )

list.Add( "PaintMaterials", "Graffitti001a" )
list.Add( "PaintMaterials", "Graffitti001b" )
list.Add( "PaintMaterials", "Graffitti001c" )
list.Add( "PaintMaterials", "Graffitti001d" )
list.Add( "PaintMaterials", "Graffitti003a" )
list.Add( "PaintMaterials", "Graffitti005a" )
list.Add( "PaintMaterials", "Graffitti006a" )
list.Add( "PaintMaterials", "Graffitti007a" )
list.Add( "PaintMaterials", "Graffitti008a" )
list.Add( "PaintMaterials", "Graffitti009a" )
list.Add( "PaintMaterials", "Graffitti010a" )
list.Add( "PaintMaterials", "Graffitti011a" )
list.Add( "PaintMaterials", "Graffitti012a" )
list.Add( "PaintMaterials", "Graffitti015a" )
list.Add( "PaintMaterials", "Graffitti017a" )
list.Add( "PaintMaterials", "Graffitti018a" )
list.Add( "PaintMaterials", "Graffitti020a" )
list.Add( "PaintMaterials", "Graffitti022a" )
list.Add( "PaintMaterials", "Graffitti023a" )
list.Add( "PaintMaterials", "Graffitti024a" )
list.Add( "PaintMaterials", "Graffitti025a" )
list.Add( "PaintMaterials", "Graffitti028a" )
list.Add( "PaintMaterials", "Graffitti031a" )
list.Add( "PaintMaterials", "Graffitti036a" )
list.Add( "PaintMaterials", "Graffitti037a" )
list.Add( "PaintMaterials", "Graffitti038a" )
list.Add( "PaintMaterials", "Graffitti043a" )
list.Add( "PaintMaterials", "Graffitti044a" )
list.Add( "PaintMaterials", "Graffitti046a" )
list.Add( "PaintMaterials", "Graffitti047a" )
list.Add( "PaintMaterials", "Graffitti049a" )
list.Add( "PaintMaterials", "Graffitti050a" )
list.Add( "PaintMaterials", "Graffitti054a" )
list.Add( "PaintMaterials", "Graffitti056a" )
list.Add( "PaintMaterials", "Graffitti059a" )
list.Add( "PaintMaterials", "Graffitti060a" )
list.Add( "PaintMaterials", "Graffitti061a" )
list.Add( "PaintMaterials", "Graffitti062a" )

-- Posters
game.AddDecal( "Poster.Breen", "decals/decal_posterbreen" )
game.AddDecal( "Poster.Combine1", "decals/decalposter014a" )
game.AddDecal( "Poster.Combine2", "decals/decalposter014b" )
game.AddDecal( "Poster.Combine3", "decals/decalposter014d" )
game.AddDecal( "Posters1", "decals/decal_posters001a" )
game.AddDecal( "Posters2", "decals/decal_posters002a" )
game.AddDecal( "Posters3", "decals/decal_posters003a" )
game.AddDecal( "Posters.Combine1", "decals/decal_posters005a" )
game.AddDecal( "Posters.Combine2", "decals/decal_posters006a" )

list.Add( "PaintMaterials", "Poster.Breen" )
list.Add( "PaintMaterials", "Poster.Combine1" )
list.Add( "PaintMaterials", "Poster.Combine2" )
list.Add( "PaintMaterials", "Poster.Combine3" )
list.Add( "PaintMaterials", "Posters1" )
list.Add( "PaintMaterials", "Posters2" )
list.Add( "PaintMaterials", "Posters3" )
list.Add( "PaintMaterials", "Posters.Combine1" )
list.Add( "PaintMaterials", "Posters.Combine2" )

-- Rugs
game.AddDecal( "Rug1", "decals/decalrug001a" )
game.AddDecal( "Rug2", "decals/decalrug002a" )
game.AddDecal( "Rug3", "decals/decalrug003a" )
game.AddDecal( "Rug4", "decals/decalrug004a" )
game.AddDecal( "Rug5", "decals/decalrug005a" )

list.Add( "PaintMaterials", "Rug1" )
list.Add( "PaintMaterials", "Rug2" )
list.Add( "PaintMaterials", "Rug3" )
list.Add( "PaintMaterials", "Rug4" )
list.Add( "PaintMaterials", "Rug5" )

-- Signs
game.AddDecal( "Sign.Fire1", "decals/decal_signfire001a" )
game.AddDecal( "Sign.Fire2", "decals/decal_signfire002a" )
game.AddDecal( "Sign.Fire3", "decals/decal_signfire006a" )
game.AddDecal( "Sign.EarProtection", "decals/decal_signprotection009a" )
game.AddDecal( "Sign.FirstAid", "decals/decal_signroute001a" )
game.AddDecal( "Sign.Arrow.UpRight", "decals/decal_signroute004a" )
game.AddDecal( "Sign.Arrow.Right", "decals/decal_signroute004b" )
game.AddDecal( "Sign.Escape", "decals/decal_signroute006a" )
game.AddDecal( "Sign.1", "decals/decal_signroute007a" )
game.AddDecal( "Sign.2", "decals/decal_signroute007b" )
game.AddDecal( "Sign.0", "decals/decal_signroute007j" )
game.AddDecal( "Sign.Level3", "decals/decalshipsign002h" )
game.AddDecal( "Sign.Storage", "decals/decalshipsign004e" )
game.AddDecal( "Sign.NoSmoking", "decals/decalshipsign005d" )
game.AddDecal( "Sign.Caution.WearYourRespirator", "decals/decalsigncaution001b" )
game.AddDecal( "Sign.Caution.AutomaticEquipment", "decals/decalsigncaution001c" )
game.AddDecal( "Sign.Danger.CraneOverhead", "decals/decalsigndanger001a" )
game.AddDecal( "Sign.Danger.RespiratorRequired", "decals/decalsigndanger001b" )
game.AddDecal( "Sign.Danger.HighVoltage", "decals/decalsigndanger001c" )
game.AddDecal( "Sign.Danger.FlammableMaterials", "decals/decalsigndanger001d" )
game.AddDecal( "Sign.Danger.AuthorizedPersonnelOnly", "decals/decalsigndanger001e" )
game.AddDecal( "Sign.Danger.Explosives", "decals/decalsigndanger001f" )
game.AddDecal( "Sign.Danger.ContaminatedArea", "decals/decalsigndanger002a" )
game.AddDecal( "Sign.Combine1", "decals/decalsignpainted001a" )
game.AddDecal( "Sign.Combine2", "decals/decalsignpainted001b" )
game.AddDecal( "Sign.Combine3", "decals/decalsignpainted001c" )
game.AddDecal( "IndustrialNumber.0", "decals/decalindustrialnumber00a" )
game.AddDecal( "IndustrialNumber.1", "decals/decalindustrialnumber01a" )
game.AddDecal( "IndustrialNumber.2", "decals/decalindustrialnumber02a" )
game.AddDecal( "IndustrialNumber.3", "decals/decalindustrialnumber03a" )
game.AddDecal( "IndustrialNumber.4", "decals/decalindustrialnumber04a" )
game.AddDecal( "IndustrialNumber.5", "decals/decalindustrialnumber05a" )
game.AddDecal( "IndustrialNumber.6", "decals/decalindustrialnumber06a" )
game.AddDecal( "IndustrialNumber.7", "decals/decalindustrialnumber07a" )
game.AddDecal( "PoliceLine", "decals/decal_policeline01a" )
game.AddDecal( "IndustrialNumber.8", "decals/decalindustrialnumber08a" )
game.AddDecal( "Sign.Atlantic", "decals/decalposter002a" )
game.AddDecal( "Sign.Zaida", "decals/decalposter003a" )
game.AddDecal( "Sign.Veikko", "decals/decalposter004a" )
game.AddDecal( "Sign.NorthernPetrol", "decals/decalposter007a" )

list.Add( "PaintMaterials", "Sign.Fire1" )
list.Add( "PaintMaterials", "Sign.Fire2" )
list.Add( "PaintMaterials", "Sign.Fire3" )
list.Add( "PaintMaterials", "Sign.EarProtection" )
list.Add( "PaintMaterials", "Sign.FirstAid" )
list.Add( "PaintMaterials", "Sign.Arrow.UpRight" )
list.Add( "PaintMaterials", "Sign.Arrow.Right" )
list.Add( "PaintMaterials", "Sign.Escape" )
list.Add( "PaintMaterials", "Sign.1" )
list.Add( "PaintMaterials", "Sign.2" )
list.Add( "PaintMaterials", "Sign.0" )
list.Add( "PaintMaterials", "Sign.Level3" )
list.Add( "PaintMaterials", "Sign.Storage" )
list.Add( "PaintMaterials", "Sign.NoSmoking" )
list.Add( "PaintMaterials", "Sign.Caution.WearYourRespirator" )
list.Add( "PaintMaterials", "Sign.Caution.AutomaticEquipment" )
list.Add( "PaintMaterials", "Sign.Danger.CraneOverhead" )
list.Add( "PaintMaterials", "Sign.Danger.RespiratorRequired" )
list.Add( "PaintMaterials", "Sign.Danger.HighVoltage" )
list.Add( "PaintMaterials", "Sign.Danger.FlammableMaterials" )
list.Add( "PaintMaterials", "Sign.Danger.AuthorizedPersonnelOnly" )
list.Add( "PaintMaterials", "Sign.Danger.Explosives" )
list.Add( "PaintMaterials", "Sign.Danger.ContaminatedArea" )
list.Add( "PaintMaterials", "Sign.Combine1" )
list.Add( "PaintMaterials", "Sign.Combine2" )
list.Add( "PaintMaterials", "Sign.Combine3" )
list.Add( "PaintMaterials", "IndustrialNumber.0" )
list.Add( "PaintMaterials", "IndustrialNumber.1" )
list.Add( "PaintMaterials", "IndustrialNumber.2" )
list.Add( "PaintMaterials", "IndustrialNumber.3" )
list.Add( "PaintMaterials", "IndustrialNumber.4" )
list.Add( "PaintMaterials", "IndustrialNumber.5" )
list.Add( "PaintMaterials", "IndustrialNumber.6" )
list.Add( "PaintMaterials", "IndustrialNumber.7" )
list.Add( "PaintMaterials", "IndustrialNumber.8" )
list.Add( "PaintMaterials", "PoliceLine" )
list.Add( "PaintMaterials", "Sign.Atlantic" )
list.Add( "PaintMaterials", "Sign.Zaida" )
list.Add( "PaintMaterials", "Sign.Veikko" )
list.Add( "PaintMaterials", "Sign.NorthernPetrol" )

-- Metal
game.AddDecal( "MetalGrate1", "decals/decalmetalgrate001a" )
game.AddDecal( "MetalGrate2", "decals/decalmetalgrate005a" )
game.AddDecal( "MetalGrate3", "decals/decalmetalgrate010a" )
game.AddDecal( "MetalGrate4", "decals/decalmetalgrate014a" )
game.AddDecal( "MetalGrate5", "decals/decalmetalgrate016a" )
game.AddDecal( "MetalGrate6", "decals/decalmetalgrate017a" )
game.AddDecal( "MetalGrate7", "decals/decalmetalgrate019a" )
game.AddDecal( "MetalGrate8", "decals/decalmetalgrate020a" )
game.AddDecal( "MetalGrate9", "decals/decalmetalgrate022a" )
game.AddDecal( "MetalHatch1", "decals/decalmetalhatch002a" )
game.AddDecal( "MetalHatch2", "decals/decalmetalhatch003a" )
game.AddDecal( "MetalHatch3", "decals/decalmetalhatch005a" )
game.AddDecal( "MetalSpeaker", "decals/decalmetalspeaker002a" )
game.AddDecal( "MetalVent1", "decals/decalmetalvent004a" )
game.AddDecal( "MetalVent2", "decals/decalmetalvent006a" )

list.Add( "PaintMaterials", "MetalGrate1" )
list.Add( "PaintMaterials", "MetalGrate2" )
list.Add( "PaintMaterials", "MetalGrate3" )
list.Add( "PaintMaterials", "MetalGrate4" )
list.Add( "PaintMaterials", "MetalGrate5" )
list.Add( "PaintMaterials", "MetalGrate6" )
list.Add( "PaintMaterials", "MetalGrate7" )
list.Add( "PaintMaterials", "MetalGrate8" )
list.Add( "PaintMaterials", "MetalGrate9" )
list.Add( "PaintMaterials", "MetalHatch1" )
list.Add( "PaintMaterials", "MetalHatch2" )
list.Add( "PaintMaterials", "MetalHatch3" )
list.Add( "PaintMaterials", "MetalSpeaker" )
list.Add( "PaintMaterials", "MetalVent1" )
list.Add( "PaintMaterials", "MetalVent2" )

-- Plaster
game.AddDecal( "Plaster.Brick.Small", { "decals/plaster015a", "decals/plaster016a" } )
game.AddDecal( "Plaster.Brick.Medium", "decals/decalbrick002d" )
game.AddDecal( "Plaster.Brick.Large", "decals/plaster020a" )
game.AddDecal( "Plaster.Brick.Bottom1", { "decals/plaster011a", "decals/plaster018a" } )
game.AddDecal( "Plaster.Brick.Bottom2", "decals/plaster013a" )
game.AddDecal( "Plaster.Brick.BottomRight", "decals/plaster012a" )
game.AddDecal( "Plaster.Brick.Left", "decals/plaster014a" )
game.AddDecal( "Plaster.Brick.TopRight", "decals/plaster019a" )
game.AddDecal( "Plaster.Small", { "decals/plaster001a", "decals/plaster004a", "decals/plaster005a", "decals/plaster006a", "decals/plaster007a", "decals/plaster008a", "decals/plaster009a", "decals/plaster010a" } )
game.AddDecal( "Plaster.Large", { "decals/decalplaster001a", "decals/decalplaster002a", "decals/plaster017a" } )
game.AddDecal( "Plaster.Wood", { "decals/decalplaster003b", "decals/decalplaster003d" } )

list.Add( "PaintMaterials", "Plaster.Brick.Small" )
list.Add( "PaintMaterials", "Plaster.Brick.Medium" )
list.Add( "PaintMaterials", "Plaster.Brick.Large" )
list.Add( "PaintMaterials", "Plaster.Brick.Bottom1" )
list.Add( "PaintMaterials", "Plaster.Brick.Bottom2" )
list.Add( "PaintMaterials", "Plaster.Brick.BottomRight" )
list.Add( "PaintMaterials", "Plaster.Brick.Left" )
list.Add( "PaintMaterials", "Plaster.Brick.TopRight" )
list.Add( "PaintMaterials", "Plaster.Large" )
list.Add( "PaintMaterials", "Plaster.Small" )
list.Add( "PaintMaterials", "Plaster.Wood" )

-- Markings
game.AddDecal( "Street1", "decals/decalstreet008a" )
game.AddDecal( "Street2", "decals/decalstreet008b" )
game.AddDecal( "LambdaSpray1", "decals/lambdaspray_1a" )
game.AddDecal( "LambdaSpray2", "decals/lambdaspray_2a" )

list.Add( "PaintMaterials", "Street1" )
list.Add( "PaintMaterials", "Street2" )
list.Add( "PaintMaterials", "LambdaSpray1" )
list.Add( "PaintMaterials", "LambdaSpray2" )

-- Other
game.AddDecal( "Crater", "decals/decal_crater001a" )
game.AddDecal( "Crater.Rollermine", "decals/rollermine_crater" )
game.AddDecal( "ConcreteDrain1", "decals/decalconcretedrain001a" )
game.AddDecal( "ConcreteDrain2", "decals/decalconcretedrain002a" )
game.AddDecal( "ConcreteDrain3", "decals/decalconcretedrain003a" )
game.AddDecal( "Porthole", "decals/decalporthole001b" )
game.AddDecal( "PowerOutlet", "decals/decalpoweroutlet001a" )
game.AddDecal( "Stain", { "decals/decalstain003a", "decals/decalstain005a", "decals/decalstain006a", "decals/decalstain007a", "decals/decalstain008a", "decals/decalstain009a", "decals/decalstain010a" } )
game.AddDecal( "TileHatch", "decals/decaltilehatch001a" )
game.AddDecal( "Extinguish", { "decals/extinguish1", "decals/extinguish2" } )
game.AddDecal( "DecompPuddle", "decals/decomp_puddle1" )
game.AddDecal( "Ivy1", "decals/ivy01" )
game.AddDecal( "Ivy2", "decals/ivy02" )
game.AddDecal( "Ivy3", "decals/ivy03" )

list.Add( "PaintMaterials", "Crater" )
list.Add( "PaintMaterials", "Crater.Rollermine" )
list.Add( "PaintMaterials", "ConcreteDrain1" )
list.Add( "PaintMaterials", "ConcreteDrain2" )
list.Add( "PaintMaterials", "ConcreteDrain3" )
list.Add( "PaintMaterials", "Porthole" )
list.Add( "PaintMaterials", "PowerOutlet" )
list.Add( "PaintMaterials", "Stain" )
list.Add( "PaintMaterials", "TileHatch" )
list.Add( "PaintMaterials", "Extinguish" )
list.Add( "PaintMaterials", "DecompPuddle" )
list.Add( "PaintMaterials", "Ivy1" )
list.Add( "PaintMaterials", "Ivy2" )
list.Add( "PaintMaterials", "Ivy3" )

--game.AddDecal( "RedGlow", "decals/redglowfade" )
--game.AddDecal( "PlasmaGlow", "decals/plasmaglowfade" )

--list.Add( "PaintMaterials", "RedGlow" )
--list.Add( "PaintMaterials", "PlasmaGlow" )

if IsMounted("tf") then
	game.AddDecal( "TF2.ArrowDown.Blue", "signs/arrow_dn_blue" )
	game.AddDecal( "TF2.ArrowDown.Red", "signs/arrow_dn_red" )
	game.AddDecal( "TF2.MannCoLogo", "overlays/mann_co_logo_001" )
	game.AddDecal( "TF2.Blood", { "decals/blood1_tf2", "decals/blood2_tf2", "decals/blood3_tf2", "decals/blood4_tf2", "decals/blood5_tf2", "decals/blood6_tf2" } )

	list.Add( "PaintMaterials", "TF2.ArrowDown.Blue" )
	list.Add( "PaintMaterials", "TF2.ArrowDown.Red" )
	list.Add( "PaintMaterials", "TF2.MannCoLogo" )
	list.Add( "PaintMaterials", "TF2.Blood" )
end

if IsMounted("cstrike") then
	game.AddDecal( "CSS.A", "decals/sitea" )
	game.AddDecal( "CSS.B", "decals/siteb" )
	game.AddDecal( "CSS.ArrowLeft", "decals/arrow_left" )
	game.AddDecal( "CSS.ArrowRight", "decals/arrow_right" )
	game.AddDecal( "CSS.ArrowUpLeft", "decals/arrowuplf" )
	game.AddDecal( "CSS.ArrowUpRight", "decals/arrowuprt" )
	game.AddDecal( "CSS.Target", "decals/target" )

	list.Add( "PaintMaterials", "CSS.A" )
	list.Add( "PaintMaterials", "CSS.B" )
	list.Add( "PaintMaterials", "CSS.ArrowLeft" )
	list.Add( "PaintMaterials", "CSS.ArrowRight" )
	list.Add( "PaintMaterials", "CSS.ArrowUpLeft" )
	list.Add( "PaintMaterials", "CSS.ArrowUpRight" )
	list.Add( "PaintMaterials", "CSS.Target" )

	game.AddDecal( "CSS.Hay", "decals/infhay" )
	game.AddDecal( "CSS.Leaves", "decals/milleaves" )
	game.AddDecal( "CSS.Sand", { "decals/sanddecal02", "decals/sanddecal03" } )
	game.AddDecal( "CSS.Snow", "decals/snow01" )

	list.Add( "PaintMaterials", "CSS.Hay" )
	list.Add( "PaintMaterials", "CSS.Leaves" )
	list.Add( "PaintMaterials", "CSS.Sand" )
	list.Add( "PaintMaterials", "CSS.Snow" )

	game.AddDecal( "CSS.Spray.Bullseye", "vgui/logos/spray_bullseye" )
	game.AddDecal( "CSS.Spray.Crosshairs", "vgui/logos/spray_crosshairs" )
	game.AddDecal( "CSS.Spray.Crybaby", "vgui/logos/spray_crybaby" )
	game.AddDecal( "CSS.Spray.Elited", "vgui/logos/spray_elited" )
	game.AddDecal( "CSS.Spray.Flashbanged", "vgui/logos/spray_flashbanged" )
	game.AddDecal( "CSS.Spray.Grenaded", "vgui/logos/spray_grenaded" )
	game.AddDecal( "CSS.Spray.Headshot", "vgui/logos/spray_headshot" )
	game.AddDecal( "CSS.Spray.Insights", "vgui/logos/spray_insights" )
	game.AddDecal( "CSS.Spray.Kamikazi", "vgui/logos/spray_kamikazi" )
	game.AddDecal( "CSS.Spray.Kilroy", "vgui/logos/spray_kilroy" )
	game.AddDecal( "CSS.Spray.Knifed", "vgui/logos/spray_knifed" )
	game.AddDecal( "CSS.Spray.Nobombs", "vgui/logos/spray_nobombs" )
	game.AddDecal( "CSS.Spray.Nosmoking", "vgui/logos/spray_nosmoking" )
	game.AddDecal( "CSS.Spray.Nowar", "vgui/logos/spray_nowar" )
	game.AddDecal( "CSS.Spray.Touchdown", "vgui/logos/spray_touchdown" )

	list.Add( "PaintMaterials", "CSS.Spray.Bullseye" )
	list.Add( "PaintMaterials", "CSS.Spray.Crosshairs" )
	list.Add( "PaintMaterials", "CSS.Spray.Crybaby" )
	list.Add( "PaintMaterials", "CSS.Spray.Elited" )
	list.Add( "PaintMaterials", "CSS.Spray.Flashbanged" )
	list.Add( "PaintMaterials", "CSS.Spray.Grenaded" )
	list.Add( "PaintMaterials", "CSS.Spray.Headshot" )
	list.Add( "PaintMaterials", "CSS.Spray.Insights" )
	list.Add( "PaintMaterials", "CSS.Spray.Kamikazi" )
	list.Add( "PaintMaterials", "CSS.Spray.Kilroy" )
	list.Add( "PaintMaterials", "CSS.Spray.Knifed" )
	list.Add( "PaintMaterials", "CSS.Spray.Nobombs" )
	list.Add( "PaintMaterials", "CSS.Spray.Nosmoking" )
	list.Add( "PaintMaterials", "CSS.Spray.Nowar" )
	list.Add( "PaintMaterials", "CSS.Spray.Touchdown" )

	game.AddDecal( "CSS.CheFace", "decals/face01" )
	game.AddDecal( "CSS.DustFlag", "decals/dustflag" )
	game.AddDecal( "CSS.DustGraffiti1", "decals/graffiti01" )
	game.AddDecal( "CSS.DustGraffiti2", "decals/graffiti02" )
	game.AddDecal( "CSS.DustGraffiti3", "decals/graffiti03" )
	game.AddDecal( "CSS.HostagePoint", "decals/hrpoint" )
	game.AddDecal( "CSS.HostagePoint_Militia", "decals/militiahostagerescue" )
	game.AddDecal( "CSS.ItalyFlag", "decals/italy_flag" )
	game.AddDecal( "CSS.OfficeSlideshow", "decals/slide" )
	game.AddDecal( "CSS.RedCarpet", "decals/tides_redcarpet" )

	list.Add( "PaintMaterials", "CSS.CheFace" )
	list.Add( "PaintMaterials", "CSS.DustFlag" )
	list.Add( "PaintMaterials", "CSS.DustGraffiti1" )
	list.Add( "PaintMaterials", "CSS.DustGraffiti2" )
	list.Add( "PaintMaterials", "CSS.DustGraffiti3" )
	list.Add( "PaintMaterials", "CSS.HostagePoint" )
	list.Add( "PaintMaterials", "CSS.HostagePoint_Militia" )
	list.Add( "PaintMaterials", "CSS.ItalyFlag" )
	list.Add( "PaintMaterials", "CSS.OfficeSlideshow" )
	list.Add( "PaintMaterials", "CSS.RedCarpet" )
end

if IsMounted("left4dead2") then
	game.AddDecal( "L4D2.BlackNumber.1", "decals/blacknumber1" )
	game.AddDecal( "L4D2.BlackNumber.2", "decals/blacknumber2" )
	game.AddDecal( "L4D2.BlackNumber.3", "decals/blacknumber3" )
	game.AddDecal( "L4D2.Checkpoint.Black", "decals/checkpoint01_black" )
	game.AddDecal( "L4D2.Checkpoint.Orange", "decals/checkpoint01_orange" )
	game.AddDecal( "L4D2.CheckpointArrow.Black", "decals/checkpointarrow01_black" )
	game.AddDecal( "L4D2.CheckpointArrow.Orange", "decals/checkpointarrow01_orange" )

	list.Add( "PaintMaterials", "L4D2.BlackNumber.1" )
	list.Add( "PaintMaterials", "L4D2.BlackNumber.2" )
	list.Add( "PaintMaterials", "L4D2.BlackNumber.3" )
	list.Add( "PaintMaterials", "L4D2.Checkpoint.Black" )
	list.Add( "PaintMaterials", "L4D2.Checkpoint.Orange" )
	list.Add( "PaintMaterials", "L4D2.CheckpointArrow.Black" )
	list.Add( "PaintMaterials", "L4D2.CheckpointArrow.Orange" )

	game.AddDecal( "L4D2.SwampLeaves", "decals/swampleaves_decal01" )
	game.AddDecal( "L4D2.TallyMarks", { "decals/days01", "decals/days02", "decals/days03" } )
	game.AddDecal( "L4D2.Blood", { "decals/blood1_l4d2", "decals/blood2_l4d2", "decals/blood3_l4d2", "decals/blood4_l4d2", "decals/blood5_l4d2", "decals/blood6_l4d2", "decals/blood7_l4d2", "decals/blood8_l4d2" } )
	game.AddDecal( "L4D2.CardsPlaying", "decals/cards_playing00" )
	game.AddDecal( "L4D2.Debris.Exterior", "decals/debris_exterior_00" )
	game.AddDecal( "L4D2.Rug", "decals/decalrug006a" )
	game.AddDecal( "L4D2.Dirt", "decals/dirt02" )
	game.AddDecal( "L4D2.DirtFloor", "decals/dirtfloor012a" )
	game.AddDecal( "L4D2.WoodDoor", "decals/door_wood35" )
	game.AddDecal( "L4D2.DrainageStain", "decals/drainage_stain_05" )
	game.AddDecal( "L4D2.Firepit", "decals/firepit" )
	game.AddDecal( "L4D2.GhostSign", "decals/ghostsign_00" )
	game.AddDecal( "L4D2.Helipad", "decals/helipad" )
	game.AddDecal( "L4D2.Hay", "decals/infhay" )
	game.AddDecal( "L4D2.Leaves", "decals/leaves02" )
	--game.AddDecal( "L4D2.", "decals/" )

	list.Add( "PaintMaterials", "L4D2.SwampLeaves" )
	list.Add( "PaintMaterials", "L4D2.TallyMarks" )
	list.Add( "PaintMaterials", "L4D2.Blood" )
	list.Add( "PaintMaterials", "L4D2.CardsPlaying" )
	list.Add( "PaintMaterials", "L4D2.Debris.Exterior" )
	list.Add( "PaintMaterials", "L4D2.Rug" )
	list.Add( "PaintMaterials", "L4D2.Dirt" )
	list.Add( "PaintMaterials", "L4D2.DirtFloor" )
	list.Add( "PaintMaterials", "L4D2.WoodDoor" )
	list.Add( "PaintMaterials", "L4D2.DrainageStain" )
	list.Add( "PaintMaterials", "L4D2.Firepit" )
	list.Add( "PaintMaterials", "L4D2.GhostSign" )
	list.Add( "PaintMaterials", "L4D2.Helipad" )
	list.Add( "PaintMaterials", "L4D2.Hay" )
	list.Add( "PaintMaterials", "L4D2.Leaves" )
	--list.Add( "PaintMaterials", "L4D2." )
end